[workspace]
    members = [
        "hello_world",
        "loops",
        "main",
        "ownership",
        "variables",
        "functions",
        "structs",
        "enums",
        "collections"]

    resolver = "3"
