[workspace]
    members = [
        "hello_world",
        "main",
        "ownership",
        "variables",
        "functions",
        "structs",
        "enums",
        "collections",
        "iters",
        ]

    resolver = "3"
