[package]
    name = "main"
    version = "0.1.0"
    edition = "2024"

[dependencies]
    hello_world = { path = "../hello_world" }
    loops = { path = "../loops" }
    variables = { path = "../variables" }
    ownership = { path = "../ownership" }
    functions = { path = "../functions" }
